### ISSUE TITLE
Szene 1e Türenbeschriftung

### ISSUE THREAD

**Issue by herzoga** [ltrn/Refucation#10]

**Comment by prosenkranz** [comment]
Im Phaser Editor das objekt markieren und bei "Properties" den "Label" aendern. Erscheint im Spiel dann ueber dem Objekt. Bei der Tuer waren zu viele Pixel transparent darueber. Das muss noch zugeschnitten werden, ansonsten schwebt das label irgendwo in der Luft.

**Comment by prosenkranz** [comment]
@herzoga wann wird das behoben?
