### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by herzoga** [ltrn/Refucation#11]
" Es soll weiterhin das Layout für das gesamte Lernspiel, also verschiedene Situationen, wie Startbildschirm, Inhaltsseite, Navigation, Lernerfolgskontrolle umgesetzt werden."

- [ ] Startbildschirm
- [x] Inhaltsseiten, Navigation
- [ ] Lernerfolgskontrolle - vermutlich Fortschrittsanzeige auf einer Karte z.B.

**Comment by prosenkranz** [comment]
Teilaufgaben hinzugefuegt.

@Luke5 kannst du bis Sonntag noch die ganz grobe Uebersichtskarte anlegen, wo einfach nur die 6 Stationen eingezeichnet sind?

**Comment by herzoga** [comment]
#45
