### ISSUE TITLE
Bugfixes

### ISSUE THREAD

**Issue by herzoga** [ltrn/Refucation#15]
Szene 1a:
- [X]  Falsches Hintegrundbild
- [x]  infobox statt alertbox

Szene 1b:
- [ ]  Texturen der Leute fehlen

Szene 1c:
- [x]  Story mit Kind fehlt	
- [ ]  mehr personen
- [x]  Dialoge gehen ueber den Bildschirm hinaus
- [X]  Dialogboxen richten
- [ ]  Newspaper text 

Szene 1e:
- [x]  Hintergrund aus Fenster fehlt
- [ ]  Vater fehlt
- [X]  Medikit & so

Szene 1f:
- [x]  Neue Assets fehlen
- [x]  Dialoge fehlen

**Comment by prosenkranz** [comment]
Ich habe fuer die noch offenen Bugs extra issues aufgemacht
