### ISSUE TITLE
API for Info Boxes to replace ugly alerts

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#16]
These boxes will show general information about the story of the game

**Comment by prosenkranz** [comment]
@herzoga bitte implementieren
```
game.showInfoBox("...");
```

**Comment by herzoga** [comment]
@prosenkranz 
Bei mir zeigt es keine Infoboxen an! 
Im jetzigen master

**Comment by herzoga** [comment]
Ich glaub weil der Text zu lang ist in der ersten Szene!

**Comment by herzoga** [comment]
`Phaser.Loader - spritesheet[hud_infobox]: error loading asset from URL assets/HUD/infobox.png`
