### ISSUE TITLE
Ziel

### ISSUE THREAD

**Issue by Luke5** [ltrn/Refucation#2]
Zielgruppe spezifizieren
Sinn des Spiels
Zu erreichendes Ziel beim Spiel

**Comment by prosenkranz** [comment]
**Zielgruppe**
Erwachsene, 18-35 Jahre alt; intrinsisch motiviert, sich ueber die Fluechtlingsrouten zu informieren

**Sinn des Spiels**
Erfahren des Verlaufs und der Situation auf der Fluechtlingsroute (Balkanroute). Informieren und (durch Arbeitsaufwand bedingt) Betroffenheit erwecken

**Zu erreichendes Ziel beim Spiel**
Ankunft im Zielland Deutschland in einem der Erstaufnahmeeinrichtungen
