### ISSUE TITLE
Scene 2a not found

### ISSUE THREAD

**Issue by herzoga** [ltrn/Refucation#24]
'Cannot instantiate scene 'scene_2a': Class not found'

Kannst du mir mal helfen @prosenkranz 
Hab es ganz normal mit dem Editor erstellt aber irgendwie findet es die nicht!

**Comment by prosenkranz** [comment]
Steht die scene_2a in der `scenes/scenes.json` drin? Die sollte da eigentlich automatisch hinzugefuegt werden, aber es kann leicht passieren, dass man die mit git zuruecksetzt / vergisst zu committen..

**Comment by prosenkranz** [comment]
Okay, hab mir deine `scene_2a.js` script datei mal angesehen.

**BITTE** ruecke korrekt ein! Dann haettest du auch gesehen, dass die schliessende Klammer von der onLoad() Funktion fehlt! ...
