### ISSUE TITLE
[Szene 2b] Die Familienobjekte sollte eigenstaendige Objekte sein (Mutter, Vater, Kind)

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#28]
Das ist noetig, damit die Dialognachrichten an den richtigen Positionen sein koennen. Andernfalls erscheinen alle Nachrichten ueber der gesamten Familie --> man kann nicht unterscheiden, wer was sagt.

**Comment by ltrn** [comment]
done
