### ISSUE TITLE
[Station 2] Sanitaeter, Schwangere Frau und Hungriger alter Mann fehlt

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#30]
- Siehe Texte.docx von @Luke5

**Comment by prosenkranz** [comment]
Die schwangere Frau koennte in dem Zelt stehen (Szene 2c). Dann muesste dort aber die Figur durch das korrekte schwangere-frau-modell ausgetauscht werden (Textur liegt in der Drive)

**Comment by prosenkranz** [comment]
Fuer den Sanitaeter habe ich in der Implementierung jetzt den Typ unten rechts in Szene 2a genommen (Der mit dem Dunkelblauen Anzug)

**Comment by ltrn** [comment]
im zelt bei 2c steht schon das mädchen. wäre also wohl sinnvoller die frau woanders zu postieren

**Comment by prosenkranz** [comment]
Welches Maedchen? Das, dem ich helfen soll auf dem Markt? Das muesste bei seiner Familie stehen. Da fehlt dann der Vater und die Mutter. - Darum wuerde ich dafuer die Familie auf Szene 2b nutzen

**Comment by prosenkranz** [comment]
@Ltrn
- [ ] Sanitaeter Textur fehlt noch
- [ ] Waerter Textur fehlt noch

**Comment by ltrn** [comment]
so. nun steht die frau schwangere im zelt und das mädchen bei der familie in szene 2b.

**Comment by prosenkranz** [comment]
Siehe #42 

Fixed in 177ce45
