### ISSUE TITLE
[Szene 2c] Hauptperson fehlt

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#31]
Fuer die Dialoge fehlt hier die Hauptperson.

Diese Person sollte direkt in der Szene drin sein - also kein extra Objekt sein, damit man sie nicht anklicken oder hovern kann

**Comment by ltrn** [comment]
hauptperson ist im background.png

**Comment by prosenkranz** [comment]
Ist noch nicht implementiert
