### ISSUE TITLE
[Szene 2a] Hauptperson steht zu weit hinten

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#33]
Wenn die Hauptperson weiter vorne steht - in etwa auf der Hoehe wie die Gruppe und Typ rechts (Sanitaeter) - sind die y-Koordinaten der Dialognachrichten auch nicht mehr so unterschiedlich

**Comment by ltrn** [comment]
ich weiß nicht ob wir die gleiche auffassung von vorne und hinten haben. aber ich habe mal versucht die figuren auf eine ebene zu setzen. wenn es passt kannst du das issue ja schließen

**Comment by prosenkranz** [comment]
Ja, das Referenzbild fuer Szene 2a sieht besser aus. Die Hauptperson und den Sanitaeter muessten dann nochmal neu ausgerendert werden - man kann im phaser editor nichts spiegeln

**Comment by ltrn** [comment]
ok. neues referenzbild ist drin und sani und die hauptperson nochmal neu als einzelbild
