### ISSUE TITLE
Arbeitspakete & Zeitplan

### ISSUE THREAD

**Issue by Luke5** [ltrn/Refucation#4]
nach https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/10879926272/CourseNode/76829240127114

Aufgaben strukturieren und an Teammitglieder aufteilen
anschließend Zeitplan erstellen aufgeschlüsselt nach Mitgliedern oder "Unterteams"

**Comment by prosenkranz** [comment]
**Concept Art + Grafiken:** Henning, Lukas
**3D Rendering:** Erich
**Implementierung:** Alexander, Erich, Pascal, Henning, Lukas
**Toolchain:** Pascal
**Protokolle:** Alexander
