### ISSUE TITLE
[Szene 3b] Dialoge

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#41]
Das ist die Szene, in der man auf dem Boot mit anderen Leuten reden kann.

**Comment by ltrn** [comment]
liegt in der drive. alles als einzelpersonen. sollten noch mehr passive menschen auf dem boot sein? also nicht anklickbar.

**Comment by prosenkranz** [comment]
Da muessen noch VIEL mehr personen drauf!

http://www.abc.net.au/news/image/6593306-3x2-700x467.jpg .....

**Comment by ltrn** [comment]
oke. aber dafür bräuchte ich auch viel mehr texturen. könnt ihr erstmal mit nem background bild arbeiten wo weniger drauf sind und das ersetzen wir dann einfach? dann nehm ich erstmal die texturen die da sind

**Comment by prosenkranz** [comment]
Die Dialoge hat Henning (oder Lukas?) in die Drive gepackt.

**Comment by prosenkranz** [comment]
Hier fehlen immernoch die Dialoge. Wann wird das erledigt? @herzoga

**Comment by herzoga** [comment]
Programmiere ich allein? @prosenkranz
