### ISSUE TITLE
Aufbau

### ISSUE THREAD

**Issue by Luke5** [ltrn/Refucation#5]
- [x] der Gameoberfläche
- [x] Mockup
- [ ] Beschreibung des "Styles"
- [x] Dialoglandkarte?

**Comment by prosenkranz** [comment]
Dialoglandkarte: Siehe #13

**Comment by prosenkranz** [comment]
Ich schliess das hier mal. Um die "Beschreibung des Styles" wird sich wohl eh keiner mehr kuemmern^^
