### ISSUE TITLE
Ring integrieren

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#55]
- Man kann den Ring einsammeln und dem Schmuggler spaeter mit geben in der Tuerkei

- Wenn man in der Tuerkei keine Chance mehr hat das Geld zu bekommen:
Schmuggler: "Du hast nicht genug Geld dabei und ich glaube kaum, dass du das hier noch zusammen kriegen wirst" --> Spiel verloren + faengt von vorne an

**Comment by herzoga** [comment]
solved with commit 0814fc09eccbb8c91865ef476c0b899232a5eef9
