### ISSUE TITLE
Scene 1b ueberarbeitete Texte implementiereen

### ISSUE THREAD

**Issue by herzoga** [ltrn/Refucation#64]

**Comment by prosenkranz** [comment]
??

Hilf mir bitte dieses Issue zu verstehen

**Comment by herzoga** [comment]
Szene 1a hat sich ja erledigt im Facebook chat

Und bei scene 1_b sollen noch andere texte rein die waren aber noch nicht fertig

**Comment by Hennrie** [comment]
welche anderen texte? Bei Szene 1b sind doch die paar leute, die einem unterschiedliche sachen erzählen. Die sind alle im text.doc zu finden.
