### ISSUE TITLE
Hilfebildschirm implementieren

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#67]
Im Treffen am Donnerstag 23.6. wurde mitgeteilt, dass diverse Spielelemente nicht intuitiv benutzbar sind. Es wurde vorgeschlagen, einen Fragezeichen-Knopf oben rechts hinzuzufuegen, auf dessen Klick ein Hilfe- Overlay angezeigt wird.

Wir brauchen also:
- [x] das Overlay (am besten 1920x1080 in Illustrator/Photoshop zusammenfrickeln)
- [x] ein Icon fuer den Fragezeichenknopf. Sollte am derzeitigen Kompass-Icon orientiert sein
- [x] die implementierung dieses Features   @prosenkranz

**Comment by Luke5** [comment]
Vorschlag für den Hilfe Icon:
https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_help_white_48px.svg

**Comment by Luke5** [comment]
Alternativ als Outline:
https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_help_outline_white_48px.svg
