### ISSUE TITLE
Leben wird selbst nach Szene 3 weiterhin automatisch abgezogen

### ISSUE THREAD

**Issue by prosenkranz** [ltrn/Refucation#73]

**Comment by herzoga** [comment]
@prosenkranz 
hab eigentlich in der Weiterleitung auf 3c 
´clearInterval();´ benutzt

**Comment by prosenkranz** [comment]
`window.clearInterval()` braucht einen parameter: Die interval id

```js
var interval = window.setInterval(...);
...
window.clearInterval(interval);
```

Siehe https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/clearInterval
